SRC += rafaelromao.c
SRC += definitions/taphold.c
SRC += features/persistent_layers.c
SRC += features/special_keys.c
SRC += features/tapdance.c
SRC += features/capslock_timer.c
SRC += features/mouselayer_toggle.c
SRC += features/os_toggle.c
SRC += features/macros.c
SRC += features/combos.c
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes # Mouse keys
EXTRAKEY_ENABLE = yes # Audio control and System control
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
NKRO_ENABLE = yes
SWAP_HANDS_ENABLE = no
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
CONSOLE_ENABLED = no
COMMAND_ENABLE = no
