SRC += rafaelromao.c
SRC += tapdance.c
SRC += capslock_timer.c
SRC += mouselayer_toggle.c
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes # Mouse keys
EXTRAKEY_ENABLE = yes # Audio control and System control
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
NKRO_ENABLE = yes
SWAP_HANDS_ENABLE = no
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
CONSOLE_ENABLED = no
COMMAND_ENABLE = no
